name: Linux WPT Tests
on:
  workflow_call:

env:
  RUST_BACKTRACE: 1
  SHELL: /bin/bash
  # These options are always constant
  CONST_BENCHER_OPTIONS: --project sagudev-servo --token ${{ secrets.BENCHER_API_TOKEN }} --testbed ubuntu-22.04

jobs:
  linux-bencher:
    name: Bencher
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        if: github.event_name != 'pull_request_target'
        with:
          fetch-depth: 0
      # This is necessary to checkout the pull request if this run was triggered via a
      # `pull_request_target` event.
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request_target'
        with:
          ref: refs/pull/${{ github.event.number }}/head
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: release-binary-linux
          path: release-binary-linux
      - name: unPackage binary
        run: tar -xzf release-binary-linux/target.tar.gz
      - name: Bootstrap dependencies
        run: |
          python3 -m pip install --upgrade pip
          sudo apt update
          sudo apt install -qy --no-install-recommends mesa-vulkan-drivers
          python3 ./mach bootstrap --skip-lints
      - uses: bencherdev/bencher@main
      - name: Set bencher opts for PRs (label try run)
        if: github.event_name == 'pull_request_target'
        run: |
            echo "RUN_BENCHER_OPTIONS=--branch '${{ github.event.number }}/PR' \
            --branch-start-point '${{ github.base_ref }}' \
            --branch-start-point-hash '${{ github.event.pull_request.base.sha }}' \
            --branch-reset \
            --github-actions '${{ secrets.GITHUB_TOKEN }}'" >> "$GITHUB_ENV"
      - name: Set bencher opts for main
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        run: |
            echo "RUN_BENCHER_OPTIONS=--branch 'main' \
            --github-actions '${{ secrets.GITHUB_TOKEN }}'" >> "$GITHUB_ENV"
      - name: Set bencher opts for try branch
        if: ${{ github.event_name == 'push' && github.ref_name == 'try' }}
        run: |
            git remote add upstream https://github.com/servo/servo
            git fetch upstream main
            echo "RUN_BENCHER_OPTIONS=--branch try \
            --branch-start-point main \
            --branch-start-point-hash $(git merge-base upstream/main HEAD) \
            --branch-reset" >> "$GITHUB_ENV"
      - name: File size
        run: bencher run --file-size ./target/release/servo --adapter json ${{ env.CONST_BENCHER_OPTIONS }} $RUN_BENCHER_OPTIONS
      - name: Speedometer
        run: |
            python3 ./mach test-speedometer -r --bmf-output speedometer.json
            bencher run --adapter json --file speedometer.json ${{ env.CONST_BENCHER_OPTIONS }} $RUN_BENCHER_OPTIONS
      - name: Dromaeo
        run: |
            python3 ./mach test-dromaeo -r --bmf-output dromaeo.json
            bencher run --adapter json --file dromaeo.json ${{ env.CONST_BENCHER_OPTIONS }} $RUN_BENCHER_OPTIONS